name: Deploy

on:
    push:
        branches: [ source ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: enrikke/gatsby-gh-pages-action@v2.1.1
              with:
                  access-token: ${{ secrets.DEPLOY_SITE }}
                  deploy-branch: master
