name: Deploy

on:
    push:
        branches: [ source ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: enriikke/gatsby-gh-pages-action@v2.1.1
              with:
                  access-token: ${{ secrets.DEPLOY_SITE }}
                  deploy-branch: master
                  node-version: 18
                  gatsby-args: --verbose
