name: Deploy

on:
    push:
        branches: [ source ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: xmflsct/action-publish-gatsby@v1
              with:
                  token: ${{ secrets.DEPLOY_SITE }}
                  publishBranch: master

